backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "type", value: "blog-post"}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Type", name: "type", widget: "hidden", required: true, default: "blog-post"}

  - name: "meeting-archive"
    label: "Meeting Archive"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter: {field: "type", value: "meeting-notes"}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ["Archive"]}
      - {label: "Type", name: "type", widget: "hidden", required: true, default: "meeting-notes"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/data-sharing/index.md"
        label: "Data Sharing"
        name: "data-sharing"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: Title, name: title, widget: string}
          - label: Data Sharing
            name: qas
            widget: list
            fields:
              - {label: Question, name: question, widget: markdown}
              - {label: Answer, name: answer, widget: markdown}
      - file: "src/pages/projects/index.md"
        label: Projects
        name: "projects"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: Intro, name: projectsIntro, widget: markdown, required: true}
          - label: Projects
            required: true
            name: projects
            widget: list
            fields:
              - {label: Title, name: title, widget: string, required: true}
              - {label: Description, name: description, widget: markdown, required: true}
              - {label: Slack Channel, name: slack-channel, widget: string, required: false}
              - label: Contact Persons
                required: true
                name: contact-persons
                widget: list
                field: {label: Name, name: name, widget: string}
      - file: "src/pages/media/index.md"
        label: "Media Coverage"
        name: "media"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - label: Media Articles
            required: true
            name: articles
            widget: list
            fields:
              - {label: News Article Title, name: title, widget: string, required: true}
              - {label: News Source, name: source, widget: string, required: true}
              - {label: News Article URL, name: url, widget: string, required: true}
              - label: News Article Date
                name: date
                widget: datetime
                dateFormat: "MMMM D, YYYY"

      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Learn and collaborate
            name: learnCollaborate
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Link, name: link, widget: string}
          - label: Data and results
            name: dataResults
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Link, name: link, widget: string}
      - file: "src/pages/publications/index.md"
        label: "Publications"
        name: "publications"
        fields:
          - label: Intro
            name: publications_page_intro
            widget: text
            required: true
          - label: Studies
            name: studies
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
                required: true
              - label: Links
                name: links
                required: true
                widget: list
                fields:
                  - {label: Description, name: description, widget: string, required: true}
                  - {label: URL, name: url, widget: string, required: true}
              - label: Posted Date
                name: posted_date
                widget: datetime
                format: Do MMMM YYYY
                required: true
              - label: Cases description
                name: cases_description
                widget: string
                required: false
              - label: Controls description
                name: controls_description
                widget: string
                required: false
              - label: Genome-wide significant loci
                name: genome_wide_significant_loci
                widget: string
                required: false
              - label: First publication
                name: first_publication
                widget: string
                required: false
      - file: "src/pages/in-silico-follow-up/index.md"
        label: "In Silico Follow-up"
        name: "in-silico-follow-up"
        fields:
          - label: Releases
            name: releases
            widget: list
            fields:
              - {name: title, label: Release title, widget: string, required: true}
              - {name: intro, label: Release intro, widget: string, required: true}
              - name: analyses
                label: Analyses
                required: true
                widget: list
                fields:
                  - {name: title, label: Analysis title, widget: string, required: true}
                  - {name: summary, label: Analysis summary, widget: markdown, required: true}
                  - name: charts
                    required: false
                    label: Charts & Graphs
                    widget: list
                    fields:
                      - {name: title, label: Graph title, widget: string, required: false}
                      - {name: description, label: Graph description, widget: markdown, required: false}
                      - name: externalImages
                        required: false
                        label: Graph images from external source
                        widget: list
                        field: {name: url, label: "External URL (e.g. https://somesite.com/image.png)", widget: string, required: true}
                      - name: internalImages
                        label: Graph images from within codebase
                        required: false
                        widget: list
                        field: {name: image, label: "Internal path (e.g. /img/image.png)", required: true}
                  - name: authors
                    required: true
                    label: Authors
                    widget: list
                    field: {name: name, label: Name, required: true}
                  - name: files
                    required: true
                    label: Files
                    widget: list
                    fields:
                      - {name: description, label: File Description (Data/README etc), widget: string, required: true}
                      - {name: filename, label: Filename, widget: string, required: true}
                      - {name: link, label: Link, widget: string, required: true}

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partners-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
