name: Periodically fetch and process new data
on:
  schedule:
    # Note: UTC time
    # https://crontab.guru/
    - cron: "15 * * * *"

jobs:
  update-data:
    name: Fetch and save contributors data
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code and submodule
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.16.0"

      # From
      # https://github.com/actions/cache/blob/b8204782bbb5f872091ecc5eb9cb7d004e35b1fa/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          # Change suffix "v1" for cache busting:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-v1
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies for contributors data fetching script
        run: cd fetchContributors && yarn --frozen-lockfile

      - name: Install dependencies for partners data fetching script
        run: cd fetchPartnersData && yarn --frozen-lockfile

      - name: Execute contributors data fetching script
        run: node fetchContributors/index.js
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

      - name: Execute partners data fetching script
        run: node fetchPartnersData/index.js
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

      - name: Commit new data and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update contributors data
          commit_author: GitHub Actions <actions@github.com>
          file_pattern: src/*
